language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - pip install nose
  - pip install webtest
  - pip install coverage
  - python setup.py develop
env:
  - NOSE_WITH_COVERAGE=1
  - NOSE_COVER_PACKAGE=restifier
script: nosetests
